language: java

install:
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
    - cd org.geppetto.model
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
    - cd org.geppetto.core
    - mvn install
    - cd .. 
    - git clone https://github.com/openworm/org.geppetto.simulation.git -b $TRAVIS_BRANCH
    - cd org.geppetto.simulation
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.datasources.git -b $TRAVIS_BRANCH
    - cd org.geppetto.datasources
    - mvn install
    - cd .. 

    
    
    
 
 


