language: java

install:
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.model.git
    - cd org.geppetto.model
    - git checkout development
    - git checkout $TRAVIS_BRANCH || true
    - travis_wait 200 mvn  -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git
    - cd org.geppetto.core
    - git checkout development
    - git checkout $TRAVIS_BRANCH || true
    - travis_wait 200 mvn  -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install
    - cd .. 
    - git clone https://github.com/openworm/org.geppetto.simulation.git
    - cd org.geppetto.simulation
    - git checkout development
    - git checkout $TRAVIS_BRANCH || true
    - travis_wait 200 mvn  -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.datasources.git
    - cd org.geppetto.datasources
    - git checkout development
    - git checkout $TRAVIS_BRANCH || true
    - travis_wait 200 mvn  -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install
    - cd .. 
    - cd uk.ac.vfb.geppetto
    - travis_wait 200 mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install

before_script:
- npm install travis-ci

after_success:
- node travis/trigger-build.js
    
    
 
 


